# Build customization
archives:
  - format: zip
    name_template: 'tfrefactor_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
builds:
  - binary: tfrefactor
    dir: tfrefactor
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    ignore:
      - goarch: '386'
        goos: darwin
    env:
      - CGO_ENABLED=0
checksum:
  name_template: 'tfrefactor_{{ .Version }}_checksums.txt'
release:
  prerelease: auto
changelog:
  skip: true
