# Build customization
builds:
  - binary: tfrefactor
    dir: tfrefactor
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    ignore:
      - goarch: '386'
        goos: darwin
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  skip: true
